// flow-typed signature: a737e9107315c8a1599fbdbc8236a994
// flow-typed version: <<STUB>>/react-skycons_v^0.7.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-skycons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-skycons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-skycons/dist/react-skycons' {
  declare module.exports: any;
}

declare module 'react-skycons/dist/ReactSkycons' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-skycons/dist/react-skycons.js' {
  declare module.exports: $Exports<'react-skycons/dist/react-skycons'>;
}
declare module 'react-skycons/dist/ReactSkycons.js' {
  declare module.exports: $Exports<'react-skycons/dist/ReactSkycons'>;
}
