// flow-typed signature: 02a90724cfba0c77c761d179a283f9b3
// flow-typed version: <<STUB>>/react-simple-loading_v^0.0.3/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-simple-loading'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-simple-loading' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-simple-loading/lib/loading' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-simple-loading/lib/loading.js' {
  declare module.exports: $Exports<'react-simple-loading/lib/loading'>;
}
